export const STYLE_ID = 'narratica-v5-shell-styles'

export const STYLES = `
.narratica-root{
  --bg:#f4f6fa;--surface:#fff;--surface2:#f8f9fc;--line:#e5e8ef;--line2:#d7dce6;
  --text:#171a21;--muted:#626b78;--muted2:#6a7380;--brand:#5367e8;--brand2:#765be8;
  --green:#0f704a;--greenbg:#eaf7f1;--amber:#87540c;--amberbg:#fff5e5;--red:#a83f49;--redbg:#fff0f1;
  --shadow:0 14px 36px rgba(25,33,52,.08);--radius:14px;--header:64px;
  --font-xs:12px;--font-sm:13px;--font-md:14px;--font-lg:16px;--font-xl:20px;--font-2xl:24px;
  --lh-tight:1.3;--lh-normal:1.5;--lh-relaxed:1.7;
  width:100%;height:100%;min-height:0;display:flex;flex-direction:column;overflow:hidden;background:var(--bg);color:var(--text);
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;font-size:var(--font-md);line-height:var(--lh-normal);text-rendering:optimizeLegibility;-webkit-text-size-adjust:100%;
}
.narratica-root,.narratica-root *{box-sizing:border-box}.narratica-root button,.narratica-root input,.narratica-root select,.narratica-root textarea{font-family:inherit;line-height:var(--lh-normal)}
.narratica-root button{cursor:pointer}.narratica-root button:disabled{cursor:not-allowed;opacity:.5}.narratica-root input::placeholder,.narratica-root textarea::placeholder{color:var(--muted2);opacity:1}
.narratica-root button:focus-visible,.narratica-root input:focus-visible,.narratica-root select:focus-visible,.narratica-root textarea:focus-visible,.narratica-root .click:focus-visible{outline:2px solid var(--brand);outline-offset:2px}
.narratica-content{flex:1;min-height:0;overflow:auto;padding:0}.grow{flex:1}.hidden{display:none!important}.click{cursor:pointer}.center{text-align:center}.top-gap{margin-top:10px}.full{width:100%}

.topbar{height:var(--header);flex:none;background:rgba(255,255,255,.96);border-bottom:1px solid var(--line);display:grid;grid-template-columns:minmax(280px,1fr) auto minmax(280px,1fr);align-items:center;gap:18px;padding:0 18px;position:relative;z-index:40;backdrop-filter:blur(12px)}
.brand-zone,.head-actions{display:flex;align-items:center;gap:9px;min-width:0}.head-actions{justify-content:flex-end}.logo{width:34px;height:34px;flex:none;border:0;border-radius:10px;background:linear-gradient(135deg,#596ef0,#835de7);color:#fff;display:grid;place-items:center;font-weight:900;box-shadow:0 8px 18px rgba(84,99,231,.24)}
.brand-text{font-size:var(--font-lg);font-weight:850;white-space:nowrap;line-height:var(--lh-tight)}.library-brand{font-size:15px}.sep{width:1px;height:25px;flex:none;background:var(--line)}
.story-switch{display:flex;align-items:center;gap:8px;border:1px solid var(--line);background:#fff;border-radius:10px;padding:7px 10px;min-width:190px;max-width:330px;text-align:left;color:var(--text)}.story-switch>div:first-child{min-width:0}.story-name{font-size:var(--font-md);font-weight:800;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.story-state{font-size:var(--font-xs);color:var(--muted);margin-top:2px}.chev{margin-left:auto;color:var(--muted);font-size:var(--font-sm)}
.mode-tabs{display:flex;align-items:center;background:#eef1f6;border-radius:12px;padding:4px;gap:3px}.mode-tab{border:0;background:transparent;padding:9px 15px;min-height:38px;border-radius:9px;font-size:var(--font-md);font-weight:800;color:#737b89;white-space:nowrap}.mode-tab.active{background:#fff;color:#242938;box-shadow:0 2px 9px rgba(30,38,60,.08)}
.icon-btn,.btn{border:1px solid var(--line);background:#fff;color:#4e5664;border-radius:9px;font-size:var(--font-sm);font-weight:760;min-height:36px;padding:8px 10px}.icon-btn{width:34px;height:34px;padding:0;display:grid;place-items:center;font-size:var(--font-lg)}.icon-btn.mini{width:28px;height:28px;min-height:28px;font-size:13px}.btn.primary{background:var(--brand);border-color:var(--brand);color:#fff}.btn.soft{background:#eef1fb;border-color:#e0e5fa;color:#4457bd}.btn.good{background:var(--greenbg);border-color:#d6eee4;color:var(--green)}.top-error{max-width:180px;color:var(--red);font-size:var(--font-xs);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.badge{display:inline-flex;align-items:center;padding:4px 7px;border-radius:999px;font-size:var(--font-xs);line-height:1.35;font-weight:800;background:#eef1f6;color:#697180;white-space:nowrap}.badge.good{background:var(--greenbg);color:var(--green)}.badge.warn{background:var(--amberbg);color:var(--amber)}.badge.red{background:var(--redbg);color:var(--red)}

.library{min-height:100%;padding:28px}.library-wrap{max-width:1180px;margin:auto}.library-head{display:flex;align-items:center;gap:12px;margin-bottom:28px}.hero{display:flex;justify-content:space-between;align-items:end;margin-bottom:16px}.hero h1{margin:0;font-size:28px;line-height:1.2}.hero p{font-size:var(--font-sm);color:var(--muted);line-height:1.6;margin:5px 0 0}.story-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.story-card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:14px;box-shadow:var(--shadow);cursor:pointer;transition:.15s}.story-card:hover{transform:translateY(-2px);border-color:#cfd6f4}.cover{height:112px;border-radius:12px;background:linear-gradient(145deg,#1d2330,#59667a);padding:12px;color:#fff;display:flex;flex-direction:column;justify-content:flex-end}.cover.b{background:linear-gradient(145deg,#2e2836,#7e688a)}.cover.c{background:linear-gradient(145deg,#20342c,#698073)}.cover-title{font-size:18px;font-weight:900}.cover-sub{font-size:var(--font-xs);line-height:1.5;opacity:.88;margin-top:4px}.story-meta{display:flex;justify-content:space-between;font-size:var(--font-xs);color:var(--muted);margin:10px 0 7px}.story-badges{display:flex;gap:6px;margin-top:10px;flex-wrap:wrap}.new-story{min-height:215px;display:grid;place-items:center;border:1px dashed #c8ceda;box-shadow:none}.new-story-title{text-align:center;font-weight:800;font-size:var(--font-sm);margin-top:9px}.plus{width:42px;height:42px;border-radius:12px;background:#eef1f6;display:grid;place-items:center;font-size:24px;color:#6f7886;margin:auto}.progress{height:6px;background:#edf0f5;border-radius:99px;overflow:hidden}.progress>span{display:block;height:100%;background:linear-gradient(90deg,#566ae8,#835ee8)}
.empty,.empty-card{color:var(--muted);font-size:var(--font-sm)}.empty{padding:30px;text-align:center}.empty-card{border:1px dashed #c8ceda;border-radius:12px;background:#fff;padding:22px;text-align:center}.empty-card strong{display:block;color:var(--text);font-size:var(--font-md)}.empty-card p{margin:6px 0 0;line-height:1.6}

.mode-view{padding:18px;min-height:100%}.page-head{display:flex;align-items:flex-start;gap:14px;margin:0 auto 14px;max-width:1500px}.page-title{font-size:var(--font-2xl);font-weight:900;line-height:1.25}.page-sub{font-size:var(--font-sm);color:var(--muted);margin-top:4px}.flow{display:flex;gap:5px;align-items:center;flex-wrap:wrap}.flow-step{border:1px solid var(--line);background:#fff;border-radius:9px;padding:7px 9px;min-height:32px;font-size:var(--font-xs);line-height:1.4;color:#767e8c}.flow-step.done{background:#f0faf6;color:#2d6e55;border-color:#d8eee5}.flow-step.current{background:#f2f4ff;color:#4055bd;border-color:#d8dfff}.subtabs{display:flex;gap:4px;padding:4px;background:#eef1f6;border-radius:10px;max-width:100%;overflow:auto}.subtab{border:0;background:transparent;padding:7px 9px;min-height:34px;border-radius:8px;font-size:var(--font-sm);font-weight:760;color:#737b89;white-space:nowrap}.subtab.active{background:#fff;color:#34404f;box-shadow:0 1px 5px rgba(30,40,60,.08)}
.panel{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);overflow:hidden}.ph{min-height:48px;padding:11px 13px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:9px}.pt{font-size:var(--font-md);font-weight:850}.ps{font-size:var(--font-xs);color:var(--muted);margin-top:2px}.pc{padding:12px}.m1grid{max-width:1500px;margin:auto;display:grid;grid-template-columns:245px minmax(500px,1fr) 310px;gap:12px}.stage-area{max-width:1500px;margin:auto}.stage-grid{display:grid;grid-template-columns:230px minmax(520px,1fr) 320px;gap:12px}.stage-content{display:none}.stage-content.active{display:block}.object-list{padding:9px}.group-label{font-size:var(--font-xs);text-transform:uppercase;color:var(--muted);padding:8px 9px 5px;letter-spacing:.04em}.row-item{padding:9px;border-radius:9px;font-size:var(--font-sm);color:#596270;display:flex;gap:8px;align-items:center;min-height:36px}.row-item:hover,.row-item.active{background:#f1f4ff;color:#354cb4}.row-button{width:100%;border:0;background:transparent;text-align:left}.row-item .mini-state{margin-left:auto;font-size:var(--font-xs);color:var(--muted)}.mini-state.ok,.ok{color:var(--green)!important}.mini-state.warn,.warn{color:var(--amber)!important}.err{color:var(--red)!important}.indent-1{margin-left:8px}.indent-2{margin-left:18px}
.editor-tools{display:flex;gap:6px;align-items:center;padding:10px 12px;border-bottom:1px solid var(--line);background:#fbfcfe;flex-wrap:wrap}.tool-btn{border:1px solid var(--line);background:#fff;border-radius:8px;padding:7px 9px;min-height:34px;font-size:var(--font-xs);font-weight:750;color:#596170}.tool-btn.accent{background:#f0f3ff;border-color:#dbe2ff;color:#3d54bf}.editor-shell{padding:15px}.chapter-meta{display:flex;align-items:center;gap:6px;margin-bottom:10px;flex-wrap:wrap}.editor{width:100%;min-height:490px;border:1px solid var(--line);border-radius:12px;padding:16px 18px;background:#fdfdfe;color:#353c47;line-height:1.85;font-size:15px;resize:vertical}.screenplay-editor{min-height:430px}.editor-footer{display:flex;align-items:center;gap:8px;margin-top:9px;flex-wrap:wrap}.actions-row{display:flex;gap:7px;margin-top:12px;align-items:center;flex-wrap:wrap}.confirm-label{font-size:var(--font-xs);display:block;margin-top:8px}
.inspector-block{padding:11px 0;border-bottom:1px solid var(--line)}.inspector-block:first-child{padding-top:0}.label{font-size:var(--font-xs);color:var(--muted);margin-bottom:6px}.value{font-size:var(--font-sm);line-height:var(--lh-relaxed);color:#555e6c}.metric-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.metric{border:1px solid var(--line);border-radius:9px;padding:8px}.metric strong{display:block;font-size:var(--font-lg)}.metric span{font-size:var(--font-xs);color:var(--muted)}.checklist{display:flex;flex-direction:column;gap:6px}.check{display:flex;justify-content:space-between;gap:8px;padding:7px 8px;min-height:34px;border:1px solid var(--line);border-radius:8px;font-size:var(--font-xs);line-height:1.45}.card-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.small-card{border:1px solid var(--line);border-radius:10px;padding:10px;background:#fbfcfe}.small-card h4{font-size:var(--font-sm);line-height:1.4;margin:0 0 5px}.small-card p{font-size:var(--font-xs);color:var(--muted);line-height:1.6;margin:0}.source-card,.decision-card,.asset-card,.shot-card,.version-card{border:1px solid var(--line);border-radius:10px;padding:10px;margin-bottom:8px;background:#fff}.source-card.active,.shot-card.active,.version-card.active{border-color:#9caaf5;background:#f8f9ff}.source-title,.shot-title{font-size:var(--font-sm);font-weight:820}.meta{font-size:var(--font-xs);color:var(--muted);line-height:1.6}.desc{font-size:var(--font-sm);color:#5b6472;margin-top:5px;line-height:1.65}.big-number{font-size:26px;font-weight:900}
.table{width:100%;border-collapse:collapse;font-size:var(--font-sm);line-height:1.5}.table th,.table td{text-align:left;padding:10px 9px;border-bottom:1px solid var(--line);vertical-align:top}.table th{color:var(--muted);font-weight:780;background:#fafbfc}.table tr:last-child td{border-bottom:0}.form-row{margin-bottom:10px}.input,.select,.textarea{width:100%;border:1px solid var(--line);border-radius:9px;padding:8px 9px;background:#fbfcfe;color:#39414d;font-size:var(--font-sm);min-height:38px;line-height:1.5}.textarea{min-height:88px;resize:vertical}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:8px}.kv{display:grid;grid-template-columns:92px 1fr;gap:6px 10px;font-size:var(--font-sm);line-height:1.55}.kv dt{color:var(--muted)}.kv dd{margin:0;color:#4e5765}
.thumb{height:62px;border-radius:8px;background:linear-gradient(145deg,#232a36,#6b778c);position:relative}.thumb.screen{background:linear-gradient(145deg,#0b0e13,#27303d)}.thumb.person{background:linear-gradient(145deg,#3b3038,#8c7180)}.shot-row{display:grid;grid-template-columns:95px 1fr auto;gap:10px;align-items:center}
.m3grid{display:grid;grid-template-columns:215px minmax(560px,1fr) 320px;gap:12px}.shot-rail{padding:8px}.rail-item{display:flex;gap:8px;align-items:center;padding:8px;border-radius:9px}.rail-item.active{background:#f1f4ff}.rail-thumb{width:42px;height:30px;border-radius:6px;background:linear-gradient(145deg,#252b36,#69768a)}.rail-name{font-size:var(--font-sm);font-weight:800}.rail-state{font-size:var(--font-xs);color:var(--muted);margin-top:2px}.preview{aspect-ratio:16/8.8;background:radial-gradient(circle at 50% 55%,#354157,#0c0f15 66%);border-radius:12px;display:grid;place-items:center;color:#fff;position:relative}.play{width:52px;height:52px;border-radius:50%;background:#fff;color:#232936;display:grid;place-items:center;font-size:18px}.preview-caption{position:absolute;bottom:10px;left:12px;font-size:var(--font-xs);color:#bac1cc}.version-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.version-card{margin:0;padding:7px;text-align:left}.vthumb{height:62px;border-radius:7px;background:linear-gradient(145deg,#272e3b,#718094);display:grid;place-items:center;color:#fff;font-size:var(--font-xs)}.vmeta{display:flex;justify-content:space-between;font-size:var(--font-xs);color:var(--muted);margin-top:5px}.queue{border:1px solid var(--line);border-radius:9px;padding:8px;margin-top:7px}.qtop{display:flex;justify-content:space-between;font-size:var(--font-xs);line-height:1.4}.qbar{height:5px;background:#edf0f5;border-radius:99px;overflow:hidden;margin-top:6px}.qbar span{display:block;height:100%;background:linear-gradient(90deg,#596ee9,#855fe7)}
.timeline{background:#171b24;border-radius:12px;padding:10px;color:#dbe0e9}.ruler{height:20px;border-bottom:1px solid #303644;font-size:var(--font-xs);line-height:1.4;color:#7f899a;display:flex;justify-content:space-between}.track{display:grid;grid-template-columns:65px 1fr;gap:8px;padding:7px 0;border-bottom:1px solid #2b303c}.track:last-child{border:0}.track-name{font-size:var(--font-xs);line-height:1.4;color:#8f98a8;padding-top:5px}.clips{display:flex;gap:4px}.clip{min-height:32px;height:auto;background:#39435c;border:1px solid #4d5873;border-radius:5px;padding:5px 7px;font-size:var(--font-xs);line-height:1.35;min-width:78px}.clip.audio{background:#334e47;border-color:#41695d}.clip.music{background:#514260;border-color:#685478}.clip.sub{background:#554b38;border-color:#746348}.offset-dialogue{margin-left:100px}.wide-ambience{min-width:330px}.offset-music{margin-left:220px;min-width:170px}.offset-sub{margin-left:155px}.audio-card{border:1px solid var(--line);border-radius:10px;padding:10px;margin-bottom:8px;display:grid;grid-template-columns:42px 1fr auto;gap:9px;align-items:center}.avatar{width:42px;height:42px;border-radius:50%;background:linear-gradient(145deg,#49536a,#9b7f91)}.avatar.environment{border-radius:10px;background:linear-gradient(145deg,#30384a,#65728a)}.avatar.music{border-radius:10px;background:linear-gradient(145deg,#4d4058,#826c8d)}
.statusbar{max-width:1500px;margin:10px auto 0;border:1px solid var(--line);background:#fff;border-radius:10px;padding:8px 10px;display:flex;gap:13px;flex-wrap:wrap;font-size:var(--font-xs);color:var(--muted);line-height:1.5;min-height:34px}

.relation-canvas{height:430px;border-radius:12px;background:radial-gradient(circle at 50% 50%,#f8f9ff,#eef1f7);position:relative}.relation-node{position:absolute;width:95px;height:50px;border:1px solid #c8cde0;border-radius:25px;background:#fff;display:grid;place-items:center;font-size:var(--font-xs);font-weight:800}.center-node{left:44%;top:42%;border-color:#aeb9f3}.ai-node{left:19%;top:20%}.family-node{right:18%;top:22%}.work-node{right:23%;bottom:17%}.relation-canvas svg{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.relation-canvas line{stroke:#b3b9c9}

.overlay{position:fixed;inset:0;background:rgba(16,20,29,.34);z-index:80;display:none}.overlay.show{display:block}.overlay-button{border:0;padding:0}.director-overlay{z-index:89}.drawer{position:fixed;top:0;right:0;width:390px;max-width:100vw;height:100vh;background:#fff;border-left:1px solid var(--line);box-shadow:-18px 0 50px rgba(20,27,45,.12);z-index:90;transform:translateX(105%);transition:.2s}.drawer.open{transform:none}.drawer-head{height:64px;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 14px;gap:9px}.drawer-head b,.modal-head b{font-size:var(--font-sm)}.drawer-body{padding:13px;overflow:auto;height:calc(100vh - 64px)}.drawer-title{font-size:var(--font-xs);color:var(--muted);font-weight:800;margin:12px 0 7px}.tool-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.tool-card{border:1px solid var(--line);border-radius:9px;padding:9px;background:#fbfcfe;text-align:left;color:var(--text)}.tool-card b{font-size:var(--font-sm);line-height:1.4}.tool-card p{font-size:var(--font-xs);color:var(--muted);margin:4px 0 0;line-height:1.6}.assistant-msg{background:#f5f7fb;border:1px solid var(--line);border-radius:10px;padding:9px;font-size:var(--font-sm);line-height:1.7;margin-bottom:8px;white-space:pre-wrap}.assistant-msg.user{background:#eef2ff;border-color:#dbe2ff;margin-left:35px}.skill-pill{display:inline-flex;border:1px solid var(--line);border-radius:999px;padding:4px 7px;margin:0 5px 5px 0;font-size:var(--font-xs);line-height:1.4;color:#596270;background:#fff}.assistant-input{display:flex;gap:7px;margin-top:12px;position:sticky;bottom:-13px;background:#fff;padding:9px 0 13px}.assistant-input .input{flex:1}.director-body{display:flex;flex-direction:column}.director-input{margin-top:auto}
.modal{position:fixed;left:50%;top:90px;transform:translateX(-50%) scale(.98);width:min(620px,calc(100vw - 36px));background:#fff;border:1px solid var(--line);border-radius:14px;box-shadow:0 24px 70px rgba(20,27,45,.22);z-index:110;display:none;overflow:hidden}.modal.open{display:block;transform:translateX(-50%) scale(1)}.story-menu{width:430px;top:88px;left:260px;transform:none}.story-menu.open{transform:none}.modal-head{min-height:52px;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 14px;gap:9px}.modal-body{padding:13px;max-height:65vh;overflow:auto}.modal-actions{padding:10px 13px;border-top:1px solid var(--line);display:flex;justify-content:flex-end;gap:7px}.story-menu-item{width:100%;display:block;text-align:left;color:var(--text)}.generic-modal{width:min(620px,calc(100vw - 36px))}.command{position:fixed;left:50%;top:90px;transform:translateX(-50%);width:min(620px,calc(100vw - 36px));background:#fff;border:1px solid var(--line);border-radius:14px;box-shadow:0 24px 70px rgba(20,27,45,.22);z-index:110;display:none;overflow:hidden}.command.open{display:block}.command input{width:100%;border:0;border-bottom:1px solid var(--line);padding:14px 15px;outline:0;font-size:var(--font-md);min-height:48px}.cmd-list{padding:8px}.cmd{width:100%;border:0;background:transparent;padding:9px;border-radius:8px;font-size:var(--font-sm);line-height:1.5;min-height:36px;display:flex;justify-content:space-between;color:#3f4754;text-align:left}.cmd:hover{background:#f2f4fa}.notice{padding:9px 10px;border:1px solid #d8e0ff;border-radius:9px;background:#f2f4ff;color:#4055bd;font-size:var(--font-sm);line-height:1.5}.error{padding:9px 10px;border:1px solid #f0cfd2;border-radius:9px;background:var(--redbg);color:var(--red);font-size:var(--font-sm);line-height:1.5}

.narratica-inspector-drawer{position:fixed;inset:0;z-index:89;pointer-events:none}.narratica-inspector-drawer:empty{display:none}.narratica-inspector-drawer>*{pointer-events:auto}.narratica-topbar{height:64px;display:flex;align-items:center;padding:0 18px;background:#fff;border-bottom:1px solid var(--line)}.narratica-head-actions{margin-left:auto}.narratica-btn{border:1px solid var(--line);background:#fff;border-radius:9px;padding:8px 10px}

@media(max-width:1180px){
  .topbar{height:auto;min-height:64px;grid-template-columns:1fr auto;padding-top:8px;padding-bottom:8px}.mode-tabs{grid-row:2;grid-column:1/-1;justify-self:center}.m1grid,.stage-grid,.m3grid{grid-template-columns:220px minmax(0,1fr)}.m1grid>.panel:last-child,.stage-grid>.panel:last-child,.m3grid>.panel:last-child{grid-column:1/-1}.story-grid{grid-template-columns:repeat(2,1fr)}.body{height:auto}
}
@media(max-width:760px){
  .library{padding:16px}.story-grid,.m1grid,.stage-grid,.m3grid{grid-template-columns:1fr}.topbar{display:flex;flex-wrap:wrap}.mode-tabs{order:3;width:100%;overflow:auto}.head-actions{margin-left:auto;flex-wrap:wrap}.page-head{flex-direction:column}.subtabs{width:100%}.m1grid>.panel:last-child,.stage-grid>.panel:last-child,.m3grid>.panel:last-child{grid-column:auto}.card-grid,.two-col,.version-grid{grid-template-columns:1fr}.story-menu{left:18px;right:18px;top:78px;width:auto;transform:none}.tool-grid{grid-template-columns:1fr}.timeline{overflow:auto}.track{min-width:620px}.offset-dialogue,.offset-music,.offset-sub{margin-left:0}.wide-ambience{min-width:160px}
}
`

export function ensureStyles(): void {
  if (document.getElementById(STYLE_ID) !== null) return
  const style = document.createElement('style')
  style.id = STYLE_ID
  style.textContent = STYLES
  document.head.appendChild(style)
}
